version: '2'
services:
  mariaDB:
        image: mariadb
        hostname: mariadb
        container_name: mariadb
        restart: always
        volumes:
          # - ./docker/mariadb/initdb/:/docker-entrypoint-initdb.d
          # - ./docker/mariadb/conf.d:/etc/mysql/conf.d
          - ./docker/mariadb/data/:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    
        ports:
          - 3306:3306
        environment:
          - TZ=Asia/Bangkok
          - MYSQL_ROOT_PASSWORD=docker
        
          - MYSQL_ROOT_HOST=% 
      
  phpmyadmin_mariadb:
        image: phpmyadmin/phpmyadmin
        links:
          - mariaDB:db
        ports:
          - 8200:80
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: docker
          PMA_HOST: mariaDB
